### PR TITLE
Enabling replacing the country list

### PR DESCRIPTION
**Pull request by nyamsprod**
- adding an optional $countries argument to the constructor
- adding the Countable Interface to determine the number of country in the collection
- adding country array validation and normalization
- adding more internal method to reuse validation and normalization everywhere in the class
- remove the use of strcasecmp since the data is normalized
- test suite is updated to take into account the new feature

### CODE REVIEW

**Comment by alcohol** [comment]
This changes far more than necessary in my humble opinion. Those who want to provide an alternate data set, probably know what they are doing, and thus validation is really not required.

**Comment by nyamsprod** [comment]
Since you don't want a simple country value object at least you should validate the input data.

Adding the validation/normalization steps enables:
- making sure your collection is always in valid state (ie if I receive a collection I'm sure the it is valid)
- catching errors earlier in your code.
- removes the need for strcasecmp (optional because it's just micro-optimisation)

**Comment by nyamsprod** [comment]
I've move the validation out in another class. So If the developer wants to validate his data prior to instantiation he can do it with the new class. Then he simply injects the new list into ISO3166 constructor

``` php
<?php

use League\ISO3166\ISO3166;
use League\ISO3166\CountryValidator;

$input_data; //some country data in an array
$validator = new CountryValidator();
$collection = new ISO3166($validator->validateMany($input_data));
```

The use of the CountryValidator is not required but highly recommended if you are not sure about your input data.

**Comment by alcohol** [comment]
I can see the use-case for a validator, though I would rather call it DataValidator, not specifically CountryValidator. Let me tinker around a bit and come up with a counter proposal.

**Comment by nyamsprod** [comment]
The names can be changed this is only a proposal 👍

**Comment by alcohol** [comment]
Can you give me your thoughts on #18?

**Comment by nyamsprod** [comment]
#18 adds the same features as this PR. So I'm closing it :+1:

**Pull request closed without merging**
