### PR TITLE
Add an alias for The Democratic Republic of the Congo

### PR DESCRIPTION
**Pull request by 8ctopus**
Add country as shown in Wikipedia

### CODE REVIEW

**Comment by alcohol** [comment]
Your screenshot does not match your suggested addition. Or do I misunderstand?

**Comment by 8ctopus** [comment]
Correct, I apologize for the overlook. It's now fixed.

**Comment by alcohol** [comment]
Thanks!

**Comment by 8ctopus** [comment]
Thank you for your work on this cool little library.

**Pull request merged**
