### PR TITLE
Library extension

### PR DESCRIPTION
**Pull request by npispas**
Extended the functionality of the library in order to support lookup by name identifier.

### CODE REVIEW

**Comment by alcohol** [comment]
I'm open to merging this PR (although I do not see much use for a lookup by name), but not in its current state:

- [ ] you should not commit the `.idea` directory (tip: add it to your [**global**](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) `.gitignore`)
- [ ] you should not have changed the name of GB, it is still the same according to ISO3166
- [ ] not sure why you added additional whitespace in that one method but it is not necessary
- [ ] in the private keys array, please put name last, not first

**Comment by npispas** [comment]
I have completed all of the above requests. The reason for such function is
because of a parser that receives a reservation which contains a country
name. The parser in turn must map the country name with the corresponding
Alpha2 identifier in order to push the reservetion to an API.

**Comment by alcohol** [comment]
Please, I said global .gitignore, not project .gitignore. I don't have the time right now to rebase this PR myself to adjust this.

**Comment by npispas** [comment]
Done Mr. Rob. Thanks in advance.

**Comment by alcohol** [comment]
Tagged as `2.1.0`: https://github.com/thephpleague/iso3166/releases/tag/2.1.0

**Pull request merged**
