### PR TITLE
public visibility for getBy

### PR DESCRIPTION
**Pull request by rap2hpoutre**
I was looking for a lib that get a country code by country name and found this one. Unfortunately, it only works from a country code to a country name. I think it could be great to search by anything. That's why I changed the visibility. One other way may be to add a `getByName` method but I'm not sure it's better.

### CODE REVIEW

**Comment by alcohol** [comment]
Sorry, it's private on purpose.

**Comment by rap2hpoutre** [comment]
Ok and what about a `getByName` ?

**Comment by alcohol** [comment]
Well, it does not make much sense honestly, since name depends on locale. The default dataset just happens to be English. Name is not actually a part of the ISO standard either, unlike alpha2/alpha3/numeric.

**Comment by alcohol** [comment]
You can always wrap an instance of the class, call `getAll()`, and search through the returned dataset :-)

**Comment by rap2hpoutre** [comment]
> You can always wrap an instance of the class, call getAll(), and search through the returned dataset :-)

That's what I done :)

**Pull request closed without merging**
